name: PatreonPlugin
version: 0.1
main: com.brandongcobb.patreonplugin.PatreonPlugin
api-version: 1.0
website: www.github.com/brandongrahamcobb
commands:
  patreon:
    description:
    usage: /patreon
    permission: patreon
